[size]
width = 10_000
height = 10_000

[start]
x = 5
y = 2

[[platform]]
x = 5
y = 2
width = 4
height = 1

[[trap]]
x = 8
y = 6
width = 10
height = 1

[[teleporter]]
x = 30
y = 2
width = 4
height = 1
target = "start"