[size]
width = 10_000
height = 10_000

[start]
x = 5
y = 2

[[platform]]
x = 3
y = 2
width = 8
height = 1

[[trap]]
x = 15
y = 10
width = 7
height = 1

[[teleporter]]
x = 30
y = 2
width = 4
height = 1
target = "end"