[size]
width = 10_000
height = 10_000

[start]
x = 2
y = 2

[[platform]]
x = 0
y = 2
width = 4
height = 1

[[trap]]
x = 4
y = 6
width = 4
height = 1

[[platform]]
x = 6
y = 8
width = 4
height = 1

[[platform]]
x = 12
y = 14
width = 4
height = 1
