[size]
width = 100
height = 100

[start]
x = 2
y = 12

[[platform]]
x = 0
y = 12
width = 4
height = 1

[[teleporter]]
x = 0
y = 11
width = 1000
height = 1
target = "start"

[[text]]
x = 4
y = 20
size = 100
value = "You have won!"