[size]
width = 10_000
height = 10_000

[start]
x = 2
y = 2

[[platform]]
x = 0
y = 2
width = 4
height = 1

[[teleporter]]
x = 0
y = 0
width = 1000
height = 1
target = "start"

[[text]]
x = 4
y = 10
size = 100
value = "You have won!"