[size]
width = 100
height = 100

[start]
x = 5
y = 12

[[platform]]
x = 3
y = 12
width = 8
height = 1

[[trap]]
x = 15
y = 20
width = 7
height = 1

[[teleporter]]
x = 30
y = 12
width = 4
height = 1
target = "end"