[size]
width = 100
height = 100

[start]
x = 2
y = 12

[[platform]]
x = 0
y = 12
width = 4
height = 1

[[trap]]
x = 4
y = 16
width = 4
height = 1

[[platform]]
x = 6
y = 18
width = 4
height = 1

[[platform]]
x = 12
y = 24
width = 4
height = 1

[[teleporter]]
x = 30
y = 20
width = 4
height = 1
target = "level_2"